version: "3.1"

services:
  rng:
    image: tksarah/dockercoins_rng:1.0
    networks:
    - dockercoins
    ports:
    - "8001:80"
    deploy:
      mode: global

  hasher:
    image: tksarah/dockercoins_hasher:1.0
    networks:
    - dockercoins
    ports:
    - "8002:80"

  webui:
    image: tksarah/dockercoins_webui:1.0
    networks:
    - dockercoins
    ports:
    - "8000:80"

  redis:
    image: redis
    networks:
    - dockercoins

  worker:
    image: tksarah/dockercoins_worker:1.0
    networks:
    - dockercoins
    deploy:
      replicas: 10
      update_config:
        parallelism: 2
        delay: 5s

networks:
    dockercoins:
